Family Name: SansMJ

Fonts:
  Light:
    MONO: 0
    CASL: 0.25
    wght: 300
    slnt: 0
    CRSV: 1

  Light Italic:
    MONO: 0
    CASL: 0.25
    wght: 300
    slnt: -13
    CRSV: 1

  Regular:
    MONO: 0
    CASL: 0.25
    wght: 400
    slnt: 0
    CRSV: 1

  Italic:
    MONO: 0
    CASL: 0.25
    wght: 400
    slnt: -13
    CRSV: 1

  Medium:
    MONO: 0
    CASL: 0.25
    wght: 500
    slnt: 0
    CRSV: 1

  Medium Italic:
    MONO: 0
    CASL: 0.25
    wght: 500
    slnt: -13
    CRSV: 1

  Demi Bold:
    MONO: 0
    CASL: 0.25
    wght: 600
    slnt: 0
    CRSV: 1

  Demi Bold Italic:
    MONO: 0
    CASL: 0.25
    wght: 600
    slnt: -13
    CRSV: 1

  Bold:
    MONO: 0
    CASL: 0.25
    wght: 700
    slnt: 0
    CRSV: 1

  Bold Italic:
    MONO: 0
    CASL: 0.25
    wght: 700
    slnt: -13
    CRSV: 1

Code Ligatures: False

Features:
- ss07
- ss09
- ss11
- ss12
- ss20
- afrc
- liga
